### ISSUE TITLE
[Revision] 8-11-2022

### ISSUE THREAD

**Issue by suryaadi44** [suryaadi44/eAD-System#68]
Todo:
- [x] Separate template domain with document (#69)
- [x] Change package naming for bootsrapper (#70)
- [x] Create individual package for utils (#71)
- [x] Move mock implementation from unit test (#72)
- [x] Use route grouping (#78)
- [x] Move routing from individual domain to one package
